"""
LLM Module

This module communicates with the local Ollama model
and returns the generated response.
"""

import ollama


def generate_answer(prompt):
    """
    Sends the prompt to the local Mistral model.

    Args:
        prompt (str): Prompt generated by the prompt builder.

    Returns:
        str: Generated answer from the LLM.
    """

    response = ollama.chat(
        model="mistral",
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ]
    )

    return response["message"]["content"]